import os
env = Environment(ENV = os.environ)
env.ParseConfig('root-config --cflags --glibs')
#env.Install('/home/wood5/evioRoot/lib', source = 'libEvioRoot')
t = env.Program(target='dmsProcess_omega', source=['dmsProcess_omega.cc','libEvioRoot.so'])
Default(t)
